--- 
title: "OBESITY ANALYSIS"
author: "SALONI GUPTA AJAY KUMAR UNI: SG3910, YOSHA SINGH TOMAR UNI: YT2741"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

A recent CDC study has shown that there is a possible link between obesity and COVID-19
risk for severe outcomes. A staggering 78% of people who were hospitalized, needed
ventilators or died due to COVID-19 in the USA, were obese/overweight [1].

This observation motivated us to dig deeper into data related to obesity trends in the USA.
Through this project, we aim to analyze the underlying trends and contributing factors
(Education, Income levels, Race etc.) that lead to obesity in adults. We also wish to study the
policy support for healthy food intake, physical activity etc. and its correlation with the
actual numbers indicating obesity/overweight classification.

In this project, we aim to focus on analysis on answering below questions:

1. Over the years how do the trends look for correlation of obesity with income,
physical activity, nutrition intake etc?
2. In recent times, how is obesity distributed across segments of
population belonging to different race, gender, age-group etc?
3. How does obesity status vary among different states in the US?
4. How environmental and policy support distributed across the US? Is there a correlation between this support and obesity rates at the state-level? 

References:

[1] "CDC study finds about 78% of people hospitalized for Covid were overweight or obese"
Link: [CDC study Covid](https://www.cnbc.com/2021/03/08/covid-cdc-study-finds-roughly-78percent-of-people-
hospitalized-were-overweight-or-obese.html "CDC study Covid")
